name: marchant
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.0+1
  shared_preferences: ^2.0.17
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  hexcolor: ^3.0.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  smooth_page_indicator: ^1.0.0+2
  geolocator: ^9.0.2
  flutter_map_location_marker: ^5.2.0+2
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.11


# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#8ed9e9"
  image: assets/images/logo4x.png
#  branding: assets/images/logo.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
